### ISSUE TITLE
Error when pip installing

### ISSUE THREAD

**Issue by brend3n** [baileymorton989/baseballforecaster#4]
I'm getting this error when trying to pip install (not sure if its a local error on my side):

![baseballforecastererror](https://user-images.githubusercontent.com/49283761/111675071-1a1f6580-87f3-11eb-8b97-0378d64a3d27.PNG)

**Comment by baileymorton989** [comment]
Thank you for catching this! I forgot to change the version number in some places and will make that change soon. Afterwards, you should be able to pip install the library.

**Comment by baileymorton989** [comment]
Try pip installing it now and see if it works. I was able to get it working on my end.

**Comment by baileymorton989** [comment]
This issue has been resolved. Thanks for pointing it out!
